                         
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "aEYpaZ1cKOoHNuTOEryw0OmwGqAz0zgyUIid3Z6>
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.7.3
    depends_on:
      - postgres
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "aEYpaZ1cKOoHNuTOEryw0OmwGqAz0zgyUIid3Z6>
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@p>
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
    volumes:
      - ./dags:/opt/airflow/dags
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create -u admin -p admin -f >

  webserver:
    image: apache/airflow:2.7.3
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "aEYpaZ1cKOoHNuTOEryw0OmwGqAz0zgyUIid3Z6>
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@p>
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver

  scheduler:
    image: apache/airflow:2.7.3
    restart: always
    depends_on:
      - webserver
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: "aEYpaZ1cKOoHNuTOEryw0OmwGqAz0zgyUIid3Z6>
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@p>
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

volumes:
  postgres-db-volume:
AIRFLOW__LOGGING__REMOTE_LOGGING: "False"

volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
  command: webserver
